--T1 remains unchanged
--Solution is for T2: SET TRANSACTION ISOLATION LEVEL REPEATABLE 

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ 
BEGIN TRAN 
SELECT * FROM Athlete
WAITFOR DELAY '00:00:05' 
SELECT * FROM Athlete
COMMIT TRAN